start_charging:
  description: "Starts charger. Also authorizes if configured to use authorization."
  fields:
    charger_id:
      description: "The charger id"
      example: "yyyyyyyy-9999-99xx-xxxx-yyyyyyyyyyyy"

stop_charging:
  description: "Starts charger. Also authorizes if configured to use authorization."
  fields:
    charger_id:
      description: "The charger id"
      example: "yyyyyyyy-9999-99xx-xxxx-yyyyyyyyyyyy"

stop_pause_charging:
  description: "New stop/pause"
  fields:
    charger_id:
      description: "The charger id"
      example: "yyyyyyyy-9999-99xx-xxxx-yyyyyyyyyyyy"

resume_charging:
  description: "New resume command."
  fields:
    charger_id:
      description: "The charger id"
      example: "yyyyyyyy-9999-99xx-xxxx-yyyyyyyyyyyy"

update_firmware:
  description: "New resume command."
  fields:
    charger_id:
      description: "Update the firmware."
      example: "yyyyyyyy-9999-99xx-xxxx-yyyyyyyyyyyy"

restart_charger:
  description: "Restart charger."
  fields:
    charger_id:
      description: "The charger id"
      example: "yyyyyyyy-9999-99xx-xxxx-yyyyyyyyyyyy"

limit_amps:
  description: "Update installation properties for 3 phases."
  fields:
    installation_id:
      description: "The installation id"
      example: "yyyyyyyy-9999-99xx-xxxx-yyyyyyyyyyyy"
    available_current_phase1:
      description: "The available current for phase 1"
      example: "16"
    available_current_phase2:
      description: "The available current for phase 2"
      example: "16"
    available_current_phase3:
      description: "The available current for phase 3"
      example: "16"
    available_current:
      description: "The available currents"
      example: "16"